export const events = [
    {
       "id": "EVT1234567890123456789",
       "name": "Jazz Night",
       "description": "Experience the smooth sounds of jazz at our cozy venue. Enjoy live performances by top jazz artists and a variety of jazz music.",
       "location": "New York",
       "date": "20th May",
       "time": '6pm - 4am',
       "price": 50,
       "thumbnail": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 30,
       "remainingSlots": 30,
       "dj": "DJ Snake",
       "foodAndDrinks": true,
       "specialPerformance": null,
       "company": "Event Company 1",
       "theme": "Jazz Night"
    },
    {
       "id": "EVT2345678901234567890",
       "name": "Reggae and Blues",
       "description": "Immerse yourself in the vibrant sounds of reggae and blues at our vintage-themed event. Enjoy live performances by renowned reggae and blues artists.",
       "location": "Los Angeles",
       "date": "25th Jun",
       "time": '1pm - 10pm',
       "price": 60,
       "thumbnail": "https://images.unsplash.com/photo-1530023367847-a683933f4172?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODh8fHBhcnRpZXN8ZW58MHx8MHx8fDA%3D",
       "slots": 25,
       "remainingSlots": 11,
       "dj": "DJ Khaled",
       "foodAndDrinks": false,
       "specialPerformance": "Samthing Soweto",
       "company": "Event Company 2",
       "theme": "Reggae and Blues"
    },
    {
       "id": "EVT3456789012345678901",
       "name": "Electronic Beats",
       "description": "Get ready to dance the night away at our electronic beats event. Featuring the latest in electronic music, this event is perfect for music enthusiasts.",
       "location": "Chicago",
       "date": "10th Jul",
       "time": '3:30pm - 12am',
       "price": 70,
       "thumbnail": "https://images.unsplash.com/photo-1583318432730-a19c89692612?q=80&w=3250&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 35,
       "remainingSlots": 27,
       "dj": "DJ Diplo",
       "foodAndDrinks": true,
       "specialPerformance": 'Serro',
       "company": "Event Company 3",
       "theme": "Electronic Beats"
    },
    {
       "id": "EVT4567890123456789012",
       "name": "Classic Rock",
       "description": "Relive the golden era of rock music at our classic rock event. Experience live performances by legendary rock bands and artists.",
       "location": "Houston",
       "date": "15th Aug",
       "time": '5pm - 12am',
       "price": 80,
       "thumbnail": "https://images.unsplash.com/photo-1527359443443-84a48aec73d2?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 40,
       "remainingSlots": 20,
       "dj": "DJ Zedd",
       "foodAndDrinks": true,
       "specialPerformance": null,
       "company": "Event Company 4",
       "theme": "Classic Rock"
    },
    {
       "id": "EVT5678901234567890123",
       "name": "Pop Concert",
       "description": "Join us for a night of pop music featuring your favorite artists. Enjoy live performances and a lively atmosphere.",
       "location": "Phoenix",
       "date": "20th Sep",
       "time": '2pm - 1am',
       "price": 90,
       "thumbnail": "https://plus.unsplash.com/premium_photo-1680790392369-ba9ae9d348db?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 20,
       "remainingSlots": 7,
       "dj": "DJ Calvin Harris",
       "foodAndDrinks": true,
       "specialPerformance": 'Fave',
       "company": "Event Company 5",
       "theme": "Pop Concert"
    },
    {
       "id": "EVT6789012345678901234",
       "name": "Country Music",
       "description": "Experience the heartfelt sounds of country music at our country music event. Enjoy live performances by top country artists.",
       "location": "Philadelphia",
       "date": "25th Oct",
       "time": '2pm - 11pm',
       "price": 100,
       "thumbnail": "https://images.unsplash.com/photo-1519111887837-a48ccf9edc00?q=80&w=3000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 15,
       "remainingSlots": 2,
       "dj": "DJ Tiesto",
       "foodAndDrinks": false,
       "specialPerformance": 'Bien Alusa',
       "company": "Event Company 6",
       "theme": "Country Music"
    },
    {
       "id": "EVT7890123456789012345",
       "name": "Hip Hop Show",
       "description": "Get ready to groove at our hip hop show. Featuring the latest in hip hop music, this event is perfect for hip hop fans.",
       "location": "San Antonio",
       "date": "10th Nov",
       "time": '1pm - 10pm',
       "price": 110,
       "thumbnail": "https://images.unsplash.com/photo-1694451353341-4d8c9c86cc31?q=80&w=3348&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 25,
       "remainingSlots": 3,
       "dj": "DJ Avicii",
       "foodAndDrinks": true,
       "specialPerformance": 'Blinky Bill',
       "company": "Event Company 7",
       "theme": "Hip Hop Show"
    },
    {
       "id": "EVT8901234567890123456",
       "name": "Latin Night",
       "description": "Experience the vibrant sounds of Latin music at our Latin night event. Enjoy live performances by top Latin artists.",
       "location": "San Diego",
       "date": "15th Dec",
       "time": '5pm - 12 am',
       "price": 120,
       "thumbnail": "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 30,
       "remainingSlots": 16,
       "dj": "DJ Steve Aoki",
       "foodAndDrinks": true,
       "specialPerformance": null,
       "company": "Event Company 8",
       "theme": "Latin Night"
    },
    {
       "id": "EVT9012345678901234567",
       "name": "R&B Jam",
       "description": "Join us for a night of R&B music featuring your favorite artists. Enjoy live performances and a lively atmosphere.",
       "location": "Dallas",
       "date": "20th Jan",
       "time": '4pm - 2am',
       "price": 130,
       "thumbnail": "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=3269&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 35,
       "remainingSlots": 9,
       "dj": "DJ Armin van Buuren",
       "foodAndDrinks": true,
       "specialPerformance": 'Karun',
       "company": "Event Company 9",
       "theme": "R&B Jam"
    },
    {
       "id": "EVT0123456789012345678",
       "name": "Folk Festival",
       "description": "Experience the rich sounds of folk music at our folk festival. Enjoy live performances by top folk artists.",
       "location": "San Jose",
       "date": "25th Feb",
       "time": '2pm - 12am',
       "price": 140,
       "thumbnail": "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?q=80&w=3176&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 40,
       "remainingSlots": 12,
       "dj": "DJ David Guetta",
       "foodAndDrinks": false,
       "specialPerformance": 'Ayrosh and Wanjine',
       "company": "Event Company 10",
       "theme": "Folk Festival"
    },
    {
       "id": "EVT1234567890123456789",
       "name": "Punk Rock",
       "description": "Get ready to rock at our punk rock event. Featuring the latest in punk music, this event is perfect for punk fans.",
       "location": "Austin",
       "date": "10th Mar",
       "time": '12pm - 12am',
       "price": 150,
       "thumbnail": "https://images.unsplash.com/photo-1495837174058-628aafc7d610?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
       "slots": 20,
       "remainingSlots": 18,
       "dj": "DJ Deadmau5",
       "foodAndDrinks": true,
       "specialPerformance": 'Njerae',
       "company": "Event Company 11",
       "theme": "Punk Rock"
    }
]